content:
- RUN conda install xeus-cling notebook openmp -c QuantStack -c conda-forge
- RUN sed -i 's/"-std=c++11"/"-std=c++11"\,\n      "-fopenmp"/' /opt/conda/share/jupyter/kernels/xeus-cling-cpp11/kernel.json
- RUN sed -i 's/"-std=c++14"/"-std=c++14"\,\n      "-fopenmp"/' /opt/conda/share/jupyter/kernels/xeus-cling-cpp14/kernel.json
- RUN sed -i 's/"-std=c++17"/"-std=c++17"\,\n      "-fopenmp"/' /opt/conda/share/jupyter/kernels/xeus-cling-cpp17/kernel.json
description: ''
name: user-custom-docker
timestamp_utc: '2019-01-16T16:46:51.410895'
